version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./ops/frontend/Dockerfile
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
  backend:
    build:
      context: ./
      dockerfile: ./ops/backend/Dockerfile
    volumes:
      - /tmp/media:/data/media
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - MEDIA_DIR=/data/media